"""Pydantic schemas for quantitative strategy signals and consensus aggregation."""

from datetime import datetime, timezone
from enum import Enum
from typing import Any, Dict, List, Optional
from pydantic import BaseModel, Field, field_validator


class SignalDirection(str, Enum):
    """Permitted quantitative signal directions."""
    LONG = "LONG"
    SHORT = "SHORT"
    HOLD = "HOLD"
    NEUTRAL = "NEUTRAL"


class TimeHorizon(str, Enum):
    """Signal validity and trade execution time horizon."""
    VERY_SHORT_TERM = "VERY_SHORT_TERM"
    SHORT_TERM = "SHORT_TERM"
    MEDIUM_TERM = "MEDIUM_TERM"
    LONG_TERM = "LONG_TERM"


class StrategySignal(BaseModel):
    """Granular signal generated by an individual quantitative strategy model."""
    strategy_name: str = Field(..., description="Name/identifier of the strategy generating the signal")
    asset: str = Field(..., description="Target asset ticker symbol (e.g. BTC)")
    direction: SignalDirection = Field(..., description="Directional bias: LONG, SHORT, HOLD, NEUTRAL")
    confidence: float = Field(
        ...,
        ge=0.05,
        le=0.95,
        description="Bounded strategy confidence [0.05, 0.95] reflecting evidence strength",
    )
    strength: float = Field(
        ...,
        ge=0.0,
        le=1.0,
        description="Signal conviction and expected magnitude [0.0, 1.0]",
    )
    time_horizon: TimeHorizon = Field(
        default=TimeHorizon.SHORT_TERM,
        description="Expected holding period / time horizon",
    )
    reasons: List[str] = Field(
        default_factory=list,
        description="Transparent quantitative factors that generated this signal",
    )
    metrics: Dict[str, float] = Field(
        default_factory=dict,
        description="Key numerical indicator values supporting the signal",
    )

    @field_validator("confidence")
    @classmethod
    def validate_confidence_bounds(cls, v: float) -> float:
        """Enforces mathematical bound [0.05, 0.95]. Confidence can never be 1.0 or 0.0."""
        if v < 0.05 or v > 0.95:
            raise ValueError(f"Confidence score {v} violates strict quantitative bounds [0.05, 0.95]")
        return round(v, 4)

    @field_validator("strength")
    @classmethod
    def validate_strength_bounds(cls, v: float) -> float:
        """Enforces mathematical bound [0.0, 1.0]."""
        if v < 0.0 or v > 1.0:
            raise ValueError(f"Strength score {v} violates bounds [0.0, 1.0]")
        return round(v, 4)


class AggregatedSignalResult(BaseModel):
    """Ensemble consensus signal combining multiple independent strategy models."""
    asset: str = Field(..., description="Asset symbol (e.g. BTC)")
    timestamp: datetime = Field(
        default_factory=lambda: datetime.now(timezone.utc),
        description="Timestamp of signal generation",
    )
    direction: SignalDirection = Field(..., description="Overall consensus directional bias")
    confidence: float = Field(
        ...,
        ge=0.05,
        le=0.95,
        description="Bounded aggregate ensemble confidence [0.05, 0.95]",
    )
    strength: float = Field(
        ...,
        ge=0.0,
        le=1.0,
        description="Aggregate signal conviction [0.0, 1.0]",
    )
    time_horizon: TimeHorizon = Field(
        default=TimeHorizon.SHORT_TERM,
        description="Aggregate recommended time horizon",
    )
    market_state: Optional[str] = Field(
        default=None,
        description="Current market regime conditioning the aggregation (e.g. BULLISH_TREND, SIDEWAYS)",
    )
    reasons: List[str] = Field(
        default_factory=list,
        description="Synthesis of primary rationale across agreeing strategies",
    )
    strategy_signals: List[StrategySignal] = Field(
        default_factory=list,
        description="Full breakdown of individual strategy outputs for complete explainability",
    )
    consensus_metrics: Dict[str, Any] = Field(
        default_factory=dict,
        description="Ensemble consensus statistics (vote counts, agreement ratio, conflict penalty)",
    )
    timeframe: str = Field(default="1h", description="Candle interval used")
    model_version: str = Field(default="v1.0", description="Signal engine version")

    @field_validator("confidence")
    @classmethod
    def validate_confidence_bounds(cls, v: float) -> float:
        """Enforces mathematical bound [0.05, 0.95]."""
        if v < 0.05 or v > 0.95:
            raise ValueError(f"Confidence score {v} violates strict quantitative bounds [0.05, 0.95]")
        return round(v, 4)

    @field_validator("strength")
    @classmethod
    def validate_strength_bounds(cls, v: float) -> float:
        """Enforces mathematical bound [0.0, 1.0]."""
        if v < 0.0 or v > 1.0:
            raise ValueError(f"Strength score {v} violates bounds [0.0, 1.0]")
        return round(v, 4)


class SignalHistoryItem(BaseModel):
    """Historical persisted quantitative signal record."""
    id: str = Field(..., description="Unique signal UUID")
    symbol: str = Field(..., description="Asset symbol")
    direction: SignalDirection = Field(..., description="Directional recommendation")
    confidence: float = Field(..., description="Recorded confidence")
    strength: float = Field(..., description="Recorded strength")
    time_horizon: str = Field(..., description="Time horizon")
    reasons: List[str] = Field(..., description="Recorded rationale")
    status: str = Field(..., description="Signal lifecycle status (e.g. ACTIVE, EXPIRED, ARCHIVED)")
    model_version: str = Field(..., description="Model version")
    timestamp: datetime = Field(..., description="Recorded signal timestamp")
